version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/source/conf.py

# Automatically build all detected versions, including dev releases
versions:
  only_active: false # This ensures RTD builds all found versions automatically
  default: latest # Keeps "latest" as default for main docs

python:
  install:
    - requirements: docs/requirements.txt
