name: Publish to PyPI and Build Docker Image

on:
  push:
    tags:
      - "v*"

jobs:
  pypi-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Extract version
        id: get_version
        run: echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV

      - name: Check if version already exists on PyPI
        id: check_version
        continue-on-error: true
        run: |
          curl -sSf https://pypi.org/pypi/alpss/${{ env.VERSION }}/json > /dev/null && echo "EXISTS=true" >> $GITHUB_ENV || echo "EXISTS=false" >> $GITHUB_ENV

      - name: Build and Publish to PyPI
        if: env.EXISTS == 'false'
        run: |
          poetry build
          poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}

      - name: Skip PyPI publish if version exists
        if: env.EXISTS == 'true'
        run: echo "Version ${{ env.VERSION }} already exists on PyPI. Skipping release."

  docker-publish:
    needs: pypi-release # Ensures PyPI release completes first
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Extract version from PyPI
        id: get_version
        run: echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Should be a member of openmsi
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            openmsi/openmsimodel:latest
            openmsi/openmsimodel:${{ env.VERSION }}
          build-args: |
            PACKAGE_VERSION=${{ env.VERSION }}
          file: ./Dockerfile
